export const Data = [
    {
        img:'/assets/Images/travel.png',
        label:"Travelings"
    },
    {
        img:'/assets/Images/WATCHES.png',
        label:"Watches"
    },
    {
        img:'/assets/Images/yacht.jpg',
        label:"Yachtes"
    },
    {
        img:'/assets/Images/YACHTS.png',
        label:"Yachts"
    },
    {
        img:'/assets/Images/yatch.jpg',
        label:"Yachts"
    },
    {
        img:'/assets/Images/Car.jpg',
        label:"Cars"
    },
    {
        img:'/assets/Images/CARS.png',
        label:"Cars"
    },
    {
        img:'/assets/Images/DIAMONDS.jpg',
        label:"Diamonds"
    },
    {
        img:'/assets/Images/JETS.jpg',
        label:"Jets"
    },
    {
        img:'/assets/Images/privateisland.png',
        label:"Private Islands"
    },
    {
        img:'/assets/Images/Property.jpg',
        label:"Properties"
    },
    {
        img:'/assets/Images/realestate.jpg',
        label:"Real Estate"
    },
    {
        img:'/assets/Images/realestate.png',
        label:"Real Estates"
    },
    {
        img:'/assets/Images/travel.png',
        label:"Travelings"
    },
    {
        img:'/assets/Images/WATCHES.png',
        label:"Watches"
    },
    {
        img:'/assets/Images/yacht.jpg',
        label:"Yachtes"
    },
    {
        img:'/assets/Images/YACHTS.png',
        label:"Yachts"
    },
    {
        img:'/assets/Images/yatch.jpg',
        label:"Yachts"
    },
];