import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import LastSection from "@/components/LastSection";
import MapSection from "@/components/MapSection";
import PageSlider from "@/components/PageSlider";
import PartnersSection from "@/components/PartnersSection";
import SliderCard from "@/components/SliderCard";
import UserIdSection from "@/components/UserIdSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <UserIdSection />
      <MapSection />
      <PartnersSection />
      <LastSection/>
    </>
  );
}
